name: 'Common setup'
description: 'Common setup routines'
runs:
  using: "composite"
  steps:
    - name: "checkout CPython"
      uses: "actions/checkout@v2"
      with:
        repository: python/cpython
        path: cpython
        ref: main
    - name: "Verify checkout"
      shell: bash
      run: |
        test -x build-python-build.sh || exit 1
        test -x cpython/configure || exit 2
    - name: Create container cache directory
      shell: bash
      run: mkdir -p /tmp/container-cache
    - name: Get data cache key
      id: get-date
      shell: bash
      run: |
        echo "::set-output name=date::$(/bin/date -u "+%Y%m%d")"
    - name: Get container cache
      id: container-cache
      uses: actions/cache@v1
      with:
        path: /tmp/container-cache
        key: image-cache-${{ steps.get-date.outputs.date }}-1
    - name: "Pull build image"
      if: ${{ steps.container-cache.outputs.cache-hit != 'true' }}
      shell: bash
      run: |
        docker pull quay.io/tiran/cpythonbuild:emsdk3
        docker save -o /tmp/container-cache/cpemsdk3.tar quay.io/tiran/cpythonbuild:emsdk3
    - name: "Load container form cache"
      if: ${{ steps.container-cache.outputs.cache-hit == 'true' }}
      shell: bash
      run: |
        docker load -i /tmp/container-cache/cpemsdk3.tar
